// function madLib()
//   {
//     var x;
// for (x = 0; x < 8; x++) { 
//   $("#"+ x + "o").text($("#" + x + "i").val());
// }

//WHAT I NEED IS A TRANS-PAGE VERSION TAHT GOES THROUGH THE INPUT VALUES AND PLACES THEM IN
//WHAT?  NEW VARIABLES?  LOCAL STORAGE?  I GUESS LOCAL STORAGE.  MAYBE ITS NOT NECESSARY
//TO HAVE A SEPERATE SCRIPT FILE.  JUST IN INDEX.HTML YOU STORE THEM, IN RESULT.HTML YOU PRINT
//THEM OUT